from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model import Model
from swagger_server import util


class Aqi(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, aqi=None):  # noqa: E501
        """Aqi - a model defined in OpenAPI

        :param aqi: The aqi of this Aqi.  # noqa: E501
        :type aqi: int
        """
        self.openapi_types = {
            'aqi': int
        }

        self.attribute_map = {
            'aqi': 'aqi'
        }

        self._aqi = aqi

    @classmethod
    def from_dict(cls, dikt) -> 'Aqi':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Aqi of this Aqi.  # noqa: E501
        :rtype: Aqi
        """
        return util.deserialize_model(dikt, cls)

    @property
    def aqi(self) -> int:
        """Gets the aqi of this Aqi.


        :return: The aqi of this Aqi.
        :rtype: int
        """
        return self._aqi

    @aqi.setter
    def aqi(self, aqi: int):
        """Sets the aqi of this Aqi.


        :param aqi: The aqi of this Aqi.
        :type aqi: int
        """

        self._aqi = aqi
