openapi: 3.0.0
info:
  title: Test Test
  description: >-
    Test Test
  version: 1.0.0
servers:
  - url: /allergic-api/v1

paths:
  /average_temp:
    get:
      summary: Return the average temperature when allergy flare-ups happened.
      operationId: controller.get_average_temp
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Temperature'
  /average_humid:
    get:
      summary: Return the average humidity when allergy flare-ups happened.
      operationId: controller.get_average_humidity
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Humidity'
  /average_aqi:
    get:
      summary: Return the average qai when allergy flare-ups happened.
      operationId: controller.get_average_aqi
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aqi'
  /average_pm10:
    get:
      summary: Return the average pm10 when allergy flare-ups happened.
      operationId: controller.get_average_pm10
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pm10'
  /average_pm25:
    get:
      summary: Return the average pm25 when allergy flare-ups happened.
      operationId: controller.get_average_pm25
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pm25'
  /average_all:
    get:
      summary: Return the average temperature, humidity, aqi, pm10 and pm25 when allergy flare-ups happened.
      operationId: controller.get_average_all
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/All'


components:
  schemas:
    Temperature:
      type: object
      example:
        temperature: 30
      properties:
        temperature:
          title: temperature
          type: number
    Humidity:
      type: object
      example:
        humidity: 70
      properties:
        humidity:
          title: humidity
          type: integer
    Aqi:
      type: object
      example:
        aqi: 90
      properties:
        aqi:
          title: aqi
          type: integer
    Pm10:
      type: object
      example:
        pm10: 80
      properties:
        pm10:
          title: pm10
          type: integer
    Pm25:
      type: object
      example:
        pm25: 159
      properties:
        pm25:
          title: pm25
          type: integer
    All:
        example:
          pm25: 159
          pm10: 80
          aqi: 90
        allOf:
          - $ref: '#/components/schemas/Temperature'
          - $ref: '#/components/schemas/Humidity'
          - $ref: '#/components/schemas/Pm25'
          - $ref: '#/components/schemas/Pm10'
          - $ref: '#/components/schemas/Aqi'
