from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model import Model
from swagger_server import util


class Pm25(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, pm25=None):  # noqa: E501
        """Pm25 - a model defined in OpenAPI

        :param pm25: The pm25 of this Pm25.  # noqa: E501
        :type pm25: int
        """
        self.openapi_types = {
            'pm25': int
        }

        self.attribute_map = {
            'pm25': 'pm25'
        }

        self._pm25 = pm25

    @classmethod
    def from_dict(cls, dikt) -> 'Pm25':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pm25 of this Pm25.  # noqa: E501
        :rtype: Pm25
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pm25(self) -> int:
        """Gets the pm25 of this Pm25.


        :return: The pm25 of this Pm25.
        :rtype: int
        """
        return self._pm25

    @pm25.setter
    def pm25(self, pm25: int):
        """Sets the pm25 of this Pm25.


        :param pm25: The pm25 of this Pm25.
        :type pm25: int
        """

        self._pm25 = pm25
