from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

import numbers
from swagger_server.models.base_model import Model
from swagger_server import util


class Temperature(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, temperature=None):  # noqa: E501
        """Temperature - a model defined in OpenAPI

        :param temperature: The temperature of this Temperature.  # noqa: E501
        :type temperature: float
        """
        if not isinstance(temperature, numbers.Number):
            raise TypeError

        if temperature > 100 or temperature < 0:
            raise ValueError

        self.openapi_types = {
            'temperature': float
        }

        self.attribute_map = {
            'temperature': 'temperature'
        }

        self._temperature = temperature

    @classmethod
    def from_dict(cls, dikt) -> 'Temperature':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Temperature of this Temperature.  # noqa: E501
        :rtype: Temperature
        """
        return util.deserialize_model(dikt, cls)

    @property
    def temperature(self) -> float:
        """Gets the temperature of this Temperature.


        :return: The temperature of this Temperature.
        :rtype: float
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature: float):
        """Sets the temperature of this Temperature.


        :param temperature: The temperature of this Temperature.
        :type temperature: float
        """

        self._temperature = temperature
